/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Asteroids.app;

import Asteroids.list.LinkedList;

import static Asteroids.utilities.StringUtils.join;
import static Asteroids.utilities.StringUtils.split;
import static Asteroids.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;



public class App {
    public static void main(String[] args) {
       MenuModel menuModel = new MenuModel();
       MenuView menuView = new MenuView();
       MenuController menuController = new MenuController(menuModel, menuView);
    }
}
